[숫자 야구 게임] 남궁혜민 미션 제출합니다.
gdsc-skhu-pair-mission/kotlin-baseball-6 pull request #2
Opened 2024-03-31 12:33 UTC by hyeminililo

어려웠던 점 
- 문제에 대해 먼저 어떤 식으로 접근 해야 할 지 구상을 한 후에,  코드를 구상하는데, 코틀린을 사용해 본 적이 없어서, 자바로 구상을 한 후에 , 코틀린으로 바꾸는 방식으로 진행했습니다.  자바와 코틀린이 같으면서 다른 부분이 꽤 있어, 이 과정이 저에게는 조금 어려웠습니다. 
- 문제에 조건이 많아서 무조건 조건문으로 처리하기에는 어려웠던 문제였던 것 같습니다. 

궁금한 점 
- 만약 게임을 다시 시작하려고 할 때,  반복문을 이용하려고 하였으나, 알 수 없는 오류가 떠서, main()을 재귀호출을 이용해 호출했습니다.  반복문을 통해 호출을 하거나 , main()을 재귀호출을 해도 되는지 등에 관해 궁금합니다
- 이번에는 test 코드가 작성되어있는 문제여서 test 코드를 사용해보면서 오류를 잡을 수 있었습니다. 그래서 test code 작성법에 대해 궁금합니다.

2024-04-01 07:46 UTC, hangillee requested changes
안녕하세요, 혜민! 👋

사용해본 적 없는 언어로 미션 진행하시느라 고생 많으셨어요! 이렇게 또 실력이 늘어가는거죠! 😁

남겨주신 질문에 대한 답변을 드릴게요!
> 만약 게임을 다시 시작하려고 할 때, 반복문을 이용하려고 하였으나, 알 수 없는 오류가 떠서, main()을 재귀호출을 이용해 호출했습니다. 반복문을 통해 호출을 하거나 , main()을 재귀호출을 해도 되는지 등에 관해 궁금합니다

당장에 마감 기한을 맞추고자 `main`을 재귀 호출 하는 건 나름 합리적인 판단이라고 생각합니다. 결론부터 말씀드리자면 **절대 이렇게 하셔서는 안됩니다.** 지금이야 프로그램의 규모가 작고, 클래스 분리도 많이 되지 않는 단순한 코드지만, 조금만 복잡해져도 언제 어디부터 재실행되어야 하는지 판단하기 어렵습니다. `main` 메소드는 프로그램의 시작점이며, 이 메소드를 재귀한다는 것은 프로그램 전체를 재귀 호출하겠다는 의미와 같습니다. 자칫 잘못하면 메모리 부족으로 프로그램이 강제 종료될 수도 있습니다. 다음부터는 오류를 해결하고 `while` 같은 제어문을 통해 메소드 내에서 반복해주세요. 재귀는 성능을 저하 시키는 가장 빠른 방법입니다.

> 이번에는 test 코드가 작성되어있는 문제여서 test 코드를 사용해보면서 오류를 잡을 수 있었습니다. 그래서 test code 작성법에 대해 궁금합니다.

테스트의 장점을 체득했군요! 축하합니다. 테스트 코드 작성법은 4월 11일 제가 직접 TDD와 클린 코드 강의를 통해 알려드릴 예정입니다. 물론, Java 기준이라 혜민에게 도움이 될지는 모르겠네요.. 다만, 거의 대부분의 언어에는 단위 테스트 라이브러리가 존재합니다. 혜민이 자주 사용하는 언어 + 단위 테스트를 구글링 해보시는 걸 추천드려요!

코드에서 수정할만한 부분을 코멘트 남겼습니다! 리팩토링 부탁드려요~

2024-04-01 07:46 UTC, hangillee commented on docs/README.md
> +  - [x] 입력을 하지 않은 경우(엔터만 쳤을 때)
기능 구현 목록 작성 👍

2024-04-01 07:46 UTC, hangillee commented on src/main/kotlin/baseball/Application.kt
> +const val END_MESSAGE = "게임 종료"
매직 리터럴 상수화 👍

2024-04-01 07:46 UTC, hangillee commented on src/main/kotlin/baseball/Application.kt
> +    while (computer.size < 3) {
`3`도 상수로 만들 수 있을 것 같습니다. 나중에 숫자 야구의 규칙이 변경 되었을 때, 해당 상수만 변경할 수 있도록 말이죠.

2024-04-01 07:46 UTC, hangillee commented on src/main/kotlin/baseball/Application.kt
> +fun compare(computer: MutableList<String>, user: List<String>): Pair<Int, Int>{
주석은 코드가 왜 그 곳에 있어야 하는지 설명하기 위해서만 존재하는 것이 더 낫습니다. 즉, 메소드 시그니처만 읽어도 어떤 역할(동작)을 하는지 알 수 있도록 코드를 작성해야 합니다. 메소드 이름이 `compareNumbersOf` 매개변수까지 포함해서 어떤 역할을 하는지 잘 알 수 있을 것 같습니다.

2024-04-01 07:46 UTC, hangillee commented on src/main/kotlin/baseball/Application.kt
> +    }
혜민은 이 분기 코드들을 읽었을 때 어떤 일을 하는지 한번에 이해할 수 있나요?

개발자는 필연적으로 다른 개발자들과 협업해야 합니다. 다른 개발자인 저는 이 코드를 처음 읽었을 때 각 분기가 어떤 역할을 하는지 이해하는데 꽤 많은 시간을 들였습니다. `else` 키워드를 의도적으로 배제하고도 충분히 구현할 수 있습니다. 대표적인 예시로 `early return` 기법이 있습니다.

`early return`에 대해서는 스스로 학습해보시길 바라며, 이 부분을 리팩토링 해봅시다!

2024-04-01 07:46 UTC, hangillee commented on src/main/kotlin/baseball/Validation.kt
> +
코드 컨벤션을 지켜야 하는 이유를 이 파일에서 찾을 수 있을 것 같아요.

한눈에 보기에도 제대로 정돈되어 있다는 느낌을 받을 수 없는 코드네요... 중괄호가 있는 코드, 없는 코드가 혼재하고 심지어는 공백 줄과 띄어쓰기도 통일성 없이 막 쓰였어요. 다시 한번 리팩토링 해봅시다.

2024-04-01 07:46 UTC, hangillee commented on src/main/kotlin/baseball/Validation.kt
> +}
무언가 이상한 표시가 있네요? EOL을 학습해봅시다!

2024-04-01 07:46 UTC, hangillee commented on src/main/kotlin/baseball/Application.kt
> +fun input(computer: MutableList<String>) :Unit{
핵심 비즈니스 로직과 출력 로직이 함께 존재하는 코드가 만들어졌네요. 나중에 비즈니스 로직(숫자 야구 규칙)이 변경되어도 이 클래스, 출력 양식이 변경되어도 이 클래스를 참조해야겠네요!

과연 바람직한 상황일까요?

2024-04-01 07:46 UTC, hangillee commented on src/main/kotlin/baseball/Validation.kt
> +        throw IllegalArgumentException()
이 예외가 왜 발생했는지 구체적인 메시지를 전달해보는 건 어떨까요?

2024-04-01 07:46 UTC, hangillee commented on src/main/kotlin/baseball/Application.kt
> +    val computer = mutableListOf<String>()
`computer`가 `mutable list`여야 할 이유가 있을까요? 값이 바뀌면 새로운 리스트를 생성하는 건 안 되나요?

2024-04-01 07:46 UTC, hangillee commented on src/main/kotlin/baseball/Application.kt
> +    val result: Pair<Int, Int> = compare(computer, user)
어느 쪽이 스트라이크고 어느 쪽이 볼인가요? 해당 자료형만 봤을 때 잘 알 수 있나요?

2024-04-04 00:46 UTC, hyeminililo commented on src/main/kotlin/baseball/Application.kt
> +    }
early return을 통해 리팩토링을 하였습니다. 그런데 계속 위에 if문이 걸려서 else 부분에 조건식을 걸어놨는데, 다른 방법이 있는지 궁금합니다 !

2024-04-04 06:04 UTC, hyeminililo commented on src/main/kotlin/baseball/Validation.kt
> +}
EOL은 줄바꿈 문자였습니다! EOL에 대해 찾아보고 학습해보니, 페어의 코드를 가져올때 생기는 문제때문에 이상한 표시가 나타났습니다. !

2024-04-04 06:06 UTC, hyeminililo commented on src/main/kotlin/baseball/Application.kt
> +fun input(computer: MutableList<String>) :Unit{
이 리뷰를 통해 비즈니스 로직과 출력 로직을 나눠서 생각했습니다. 그래서 리팩토링 과정에서는 하나의 기능만 담당하는 메소드로 리팩토링을 진행했습니다.

2024-04-04 06:09 UTC, hyeminililo commented on src/main/kotlin/baseball/Application.kt
> +    val computer = mutableListOf<String>()
이 피드백을 듣고, 컴퓨터 초기 변수를 list로 선언하고, 바로 랜덤숫자를 넣고 싶었지만, 그 과정이 힘들고 잘 모르겠어서, mutablelist로 선언한뒤 변수를 받는 부분에서는 toList함수를 통해 list로 저장했습니다.  mutablelist를 사용하지 않고, list의 원소로 랜덤 수를 받는 방법이 있는지 궁금합니다 !

2024-04-04 07:33 UTC, hangillee requested changes
안녕하세요, 혜민! 👋

미션하느라 고생하셨어요. 코멘트 남겨드린 부분 조금 더 수정해봅시다.

2024-04-04 07:33 UTC, hangillee commented on src/main/kotlin/baseball/Application.kt
> +    val computer = mutableListOf<String>()
Kotlin의 언어 특성상 값이 변화하려면 `mutableListOf`를 사용해서 자료형을 선언해야 하죠... 제가 Kotlin을 잘 알지 못해서 정확한 답은 드리기 어렵지만, Java 기준으로는 새로운 값을 가진 객체를 생성하는 것 정도로 말씀드릴 수 있을 것 같습니다.

지금 당장은 해당 코드를 수정할 필요는 없을 것 같습니다.

2024-04-04 07:33 UTC, hangillee commented on src/main/kotlin/baseball/Application.kt
> +fun input(computer: MutableList<String>) :Unit{
객체까지도 분리할 수 있지 않았을까요?

2024-04-04 07:33 UTC, hangillee commented on src/main/kotlin/baseball/Validation.kt
> +}
좋습니다! 이 이상한 표시를 없애려면 간단하게 모든 코드의 마지막 줄은 공백 라인으로 두면 됩니다!

2024-04-04 07:33 UTC, hangillee commented on src/main/kotlin/baseball/Application.kt
> +    }
주석이 필요없도록 리팩토링 해볼 수 있지 않을까요?

2024-04-04 07:33 UTC, hangillee commented on src/main/kotlin/baseball/Application.kt
> +fun gameRestart(){
지금 메소드 사이에 개행이 없어요. 적절한 개행도 코드 컨벤션에서는 매우 중요한 요소입니다. 사소하다고 생각할 수 있지만, 가독성에 큰 영향을 줍니다. 앞으로는 개행에 신경 써봅시다.

2024-04-04 07:33 UTC, hangillee commented on src/main/kotlin/baseball/Validation.kt
> +
필요 없는 공백을 없애봅시다.

2024-04-04 07:33 UTC, hangillee commented on src/main/kotlin/baseball/Application.kt
> +            inputUser(computer)
들여쓰기 일관성이 없네요.. 이런 사소한 부분도 대부분의 회사, 팀에서는 컨벤션으로 지정되어 있습니다.

2024-04-04 08:26 UTC, hyeminililo commented on src/main/kotlin/baseball/Application.kt
> +fun input(computer: MutableList<String>) :Unit{
inputUser 함수 안에 , 사용자에게 입력받기, 유효성 검사, 게임 결과 호출을 하는 3가지의 기능을 가지고 있는데 이것을 조금 더 분리하면 좋다는 말씀일까요 ?!

2024-04-04 08:51 UTC, hangillee commented on src/main/kotlin/baseball/Application.kt
> +    }
`else` 자체를 안 쓸 수 있습니다! 다음 미션에서 적용해봅시다!

2024-04-04 08:51 UTC, hangillee commented on src/main/kotlin/baseball/Application.kt
> +fun input(computer: MutableList<String>) :Unit{
각각의 기능을 하나씩 가지고 있는 객체를 생성하는 것도 방법이 될 수 있겠죠 😁

2024-04-04 08:53 UTC, hangillee commented
미션하느라 고생했어요!

남겨드린 코멘트는 다음 미션에서 잘 적용해봅시다!

2024-04-04 08:53 UTC, merged