[숫자 야구 게임] 이인협 미션 제출합니다.
gdsc-skhu-pair-mission/kotlin-baseball-6 pull request #3
Opened 2024-04-01 08:31 UTC by cucumber99

## 어려웠던 점
- MVC 패턴을 구현하고자 모델을 가능한 한 세분화 하였는데, 올바른 방법인지 아직 헷갈립니다.
- 생성한 난수와 사용자가 입력한 값을 비교하고 결과값을 효율적으로 제어하기 위해 'Answer' 라는 모델을 구현하였는데, 새롭게 계산할 때마다 객체를 초기화하는 방식을 사용하여 비효율적이라고 생각됩니다. 이 부분을 어떻게 개선해야 할지 궁금합니다.
- 중복되는 코드가 있는 것 같은데, 어떻게 줄여 나가야 할지 궁금합니다.
- 클래스나 메소드, 변수 네이밍이 적절하지 못한 부분이 조금 있는 것 같습니다.

2024-04-02 03:11 UTC, hangillee requested changes
안녕하세요, 인협! 👋

Kotlin 학습하시면서 미션 수행하느라 고생하셨습니다! 프로그래밍 언어는 처음 공부할 때가 가장 어려운 것 같습니다. 앞으로도 Kotlin 학습 파이팅입니다!

남겨주신 질문에 대한 답변입니다!

> MVC 패턴을 구현하고자 모델을 가능한 한 세분화 하였는데, 올바른 방법인지 아직 헷갈립니다.

MVC 패턴이 등장한 이유가 무엇인가요? MVC 패턴은 무엇을 MVC 패턴이라고 하나요? Model은 무슨 역할을 하고, View, Controller는 무슨 책임을 가지나요? 왜 올바른 방법인지 아닌지 헷갈렸나요? 인협이 MVC 패턴에 대해 아는 내용을 설명해주시고 왜 올바르지 않은 방법처럼 느꼈는지 말씀해주세요.

> 생성한 난수와 사용자가 입력한 값을 비교하고 결과값을 효율적으로 제어하기 위해 'Answer' 라는 모델을 구현하였는데, 코드를 작성하고 보니 그렇게 효율적이지 못하다고 생각합니다. 더 나아질 방안이 있는지 궁금합니다.

왜 비효율적이라고 생각했나요? 저는 `Answer` 클래스가 매우 핵심적인 비즈니스 로직을 가지고 있는 객체로 보이고, 알맞은 역할과 책임을 가지는 객체로 잘 분리된 것 같아요. 다만 이름이 왜 `Answer`였어야 했는지는 의문이네요. 인협이 생각하는 효율적인 코드는 어떤 코드인가요?

> 중복되는 코드가 있는 것 같은데, 어떻게 줄여 나가야 할지 궁금합니다.

가장 쉬운 방법은 메소드 분리를 통해 중복되는 코드들을 메소드 호출로 대체하는 것입니다. 중복되는 코드가 많아진다는 것은 리팩토링의 신호로, 클래스 분리, 추상화 등의 다른 방법도 활용해봅시다!

> 클래스나 메소드, 변수 네이밍이 적절하지 못한 부분이 조금 있는 것 같습니다.

이건 거의 모든 개발자들이 대다수의 시간을 쏟는 부분 같아요. 결국 코드는 누군가가 읽어야 하는데 네이밍 규칙이 제멋대로인 코드는 읽기 힘들어지겠죠. 한번 깊게 고민해보는 것도 추천합니다.

> 코틀린의 공식 문서에서도 getter를 지양하라고 하였는데, getter를 사용하지 않고 객체가 일을 하게 한다는 것을 아직 잘 구현하지 못하겠습니다. (이게 제일 궁금함)

`getter`를 지양하고 메시지를 전달하라는 의미는 결국 객체 내부 상태를 외부에서 알지 못하게 하라는 것과 일맥 상통하는 말입니다. 즉, `getter`를 통해 어떤 객체 내부의 값을 가져와서 외부 객체가 이를 활용하는 것보다 객체가 스스로 동작하고 그 결과를 반환하는게 낫다는 의미입니다.

예를 들어,
```java
class Account(final int money) {
    private int amout = 0;

    public int getAmount() {
        return this.amount;
    }

    public void setAmount(final int newAmount) {
        this.amount = newAmount;
    }
}
```

이런 객체 설계 보다는

```java
class Account(final int money) {
    private int amout = 0;

    public void add(final int income) {
        this.amount += income;
    }
}
```
이 설계가 낫다는 의미입니다.

객체지향은 사실 역할과 책임을 어떻게 객체에 부여하고 이를 적절하게 나눌 것인지가 가장 어렵습니다. 개발자마다 생각도 모두 달라서 확실한 정답은 없습니다. 앞으로 꾸준하게 자신만의 기준을 세우는 것이 중요합니다. 물론 정답은 없어도 오답은 있습니다! 😁

2024-04-02 03:11 UTC, hangillee commented on docs/README.md
> +  - 3개의 숫자가 일치할 경우 종료 문구 출력
기능 구현 목록 작성 👍

2024-04-02 03:11 UTC, hangillee commented on src/main/kotlin/baseball/controller/Controller.kt
> +        } while (flag.flag)
`flag.flag`가 뭘 의미하는지 이 코드만 읽었을 때는 이해하기 어렵습니다. 코드는 그 자체로 읽었을 때 의미가 명확해야 합니다. 이는 **축약 금지**라는 이름의 규칙으로 컨벤션이 되기도 합니다. 즉, 메소드 이름과 변수 이름이 길어지더라도 축약하지 않고 있는 그대로의 뜻을 보여주는게 훨씬 낫다는 것입니다.

단순히 `flag.flag`로는 이게 `Boolean`일 뿐 무엇의 `flag`인지 전혀 알 수 없습니다..

2024-04-02 03:11 UTC, hangillee commented on src/main/kotlin/baseball/controller/Controller.kt
> +            }
`indent`(들여쓰기)를 줄일 수 있는 방법이 있지 않을까요?

2024-04-02 03:11 UTC, hangillee commented on src/main/kotlin/baseball/controller/Controller.kt
> +    private fun getGameFlag() { //게임 플래그 입력
주석은 해당 코드가 왜 여기에 있어야 하는지 설명하기 위해 작성하는 것이 좋습니다. 메소드 시그니처만으로도 동작을 이해할 수 있도록 리팩토링 해봅시다!

2024-04-02 03:11 UTC, hangillee commented on src/main/kotlin/baseball/controller/Controller.kt
> +                flag.setFlag(input)
`setter`보단 **정적 팩토리 메소드**나 **생성자**를 활용해봅시다.
관련된 개념으로는 불변 객체(immutable object)에 대해 학습해봅시다!

2024-04-02 03:11 UTC, hangillee commented on src/main/kotlin/baseball/controller/Controller.kt
> +}
EOL에 대해서 학습해봅시다!

2024-04-02 03:11 UTC, hangillee commented on src/main/kotlin/baseball/model/Answer.kt
> +            }
이 친구들은 메소드로 분리할 수 있을 것 같습니다. 각 `if`문 하나씩 메소드로 분리하고 메소드 시그니처를 통해 의미를 부여하면 `for` 반복에서 무슨 동작을 하는지 한 눈에 알아보기 쉬울 것 같습니다.

힌트는..
```kotlin
fun countStrike(answerValue: Char, inputValue: Char) {
    if (answerValue == inputValue) {
        _strikeCount++
    }
}
```

2024-04-02 03:11 UTC, hangillee commented on src/main/kotlin/baseball/model/Number.kt
> +            }
Kotlin에도 해당 Collection이 있는지는 모르겠지만 Java의 `Set`과 같은 집합 컬렉션을 활용한다면 쉽게 중복을 제거할 수 있지 않을까요?

2024-04-02 03:11 UTC, hangillee commented on src/main/kotlin/baseball/model/User.kt
> +    }
`getter`는 몰라도 `setter`는 예외 없이 지양하는게 좋습니다.

2024-04-02 03:11 UTC, hangillee commented on src/main/kotlin/baseball/util/Constants.kt
> +    const val SEPARATOR = ""
상수를 한 곳에 모아두고 관리하는게 **지금은** 편리하고 좋을 수 있습니다.
그러나, 조금만 규모가 커지면 지금보다 상수가 훨씬 많아질 수도 있고,
나중에는 "어떤 도메인에서 사용되는 무슨 상수를 수정해주세요."와 같은 요청이 들어오면
빽빽해진 상수 목록에서 겨우겨우 도메인 코드와 비교해가며 수정하려는 상수를 찾아야 합니다.
그마저도 잘못된 상수를 건드려버리면 대참사가 일어날 수도 있죠..

차라리 상수를 사용하는 클래스에 두는게 더 나을 수 있습니다.

2024-04-02 03:11 UTC, hangillee commented on src/main/kotlin/baseball/util/Validator.kt
> +    }
마찬가지로 주석 보다는 메소드 시그니처만 읽어도 무슨 역할을 하는지 알 수 있게 해주세요. 지금은 몇몇 메소드를 제외하곤 주석이 없어도 뭘 검증하는지 충분히 알 수 있습니다! 주석을 지우고 메소드 이름을 더 풍부하게 작성해주세요.

2024-04-02 03:11 UTC, hangillee commented on src/main/kotlin/baseball/view/Output.kt
> +            else -> println("${strike}${STRIKE_MESSAGE}")
`early return`을 사용한다면 `else` 없이도 가능하지 않을까요?

2024-04-02 10:41 UTC, cucumber99 commented on src/main/kotlin/baseball/controller/Controller.kt
> +    private fun getGameFlag() { //게임 플래그 입력
페어와의 원활한 코딩을 위해 주석을 적어놨는데, 이 부분은 개선해 보겠습니다.

2024-04-02 10:42 UTC, cucumber99 commented on src/main/kotlin/baseball/util/Constants.kt
> +    const val SEPARATOR = ""
습관을 잘못 들인 것 같습니다. 추후에는 상수까지 모두 분리해 볼게요

2024-04-02 10:47 UTC, cucumber99 commented on src/main/kotlin/baseball/model/Answer.kt
> +            }
해당 메소드에서 if로 처리하는 것 보다 분리된 메소드에 인자로 전달하는 것이 더 명확해 보이긴 하네요. 감사합니다.

2024-04-02 10:50 UTC, cucumber99 commented
> 왜 비효율적이라고 생각했나요? 저는 Answer 클래스가 매우 핵심적인 비즈니스 로직을 가지고 있는 객체로 보이고, 알맞은 역할과 책임을 가지는 객체로 잘 분리된 것 같아요. 다만 이름이 왜 Answer였어야 했는지는 의문이네요. 인협이 생각하는 효율적인 코드는 어떤 코드인가요?

해당 클래스로 생성한 객체는 사용자의 입력이 들어올 때마다 사용자의 입력과 정답을 비교하여 결과를 전달하게 되는데, 객체가 갖고 있는 데이터 (볼, 스트라이크 카운트) 를 초기화하기 위해서 initCount라는 메소드를 통해 매번 0으로 초기화한 다음 값을 비교하게끔 했습니다. 이 부분이 비효율적이라고 생각했습니다.

2024-04-04 07:40 UTC, hangillee approved these changes
안녕하세요, 인협! 👋

리팩토링 잘 진행해 주셨네요! 한 번 해본 미션이지만 페어 프로그래밍은 처음이라 힘들었을 거라고 생각합니다. 다음 미션도 파이팅입니다!

2024-04-04 07:40 UTC, hangillee commented on src/main/kotlin/baseball/model/Answer.kt
> +        val answer = number.randomNumber
명시적인 네이밍 👍

2024-04-04 07:40 UTC, merged